version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mongo-data:/data/db

    rmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
